### ISSUE TITLE
page not clearing when searching for another user

### ISSUE THREAD

**Issue by ahoat** [ahoat/github-analyser#3]
The page is not resetting when searching for a new user.
creates more elements and stacks them

**Comment by lascellesabercrombie** [comment]
This was the main thing I spotted. I think you can fix it by setting the headlineData .textContent to an empty string at the beginning of the headlines function (e.g. line43: headlineData.textContent = ""). You'll need to do something similar for the stars to avoid doubling there!

**Comment by ahoat** [comment]
Fab.  Thank you Alex!
I initially used a while loop to clear the child nodes but your solution worked way better and is more elegant.
