### ISSUE TITLE
Review :)

### ISSUE THREAD

**Issue by mariaalouisaa** [ahoat/github-analyser#5]
- HTML, CSS & JS files are all very clear and easy to read. Well named variables help to follow the JS also!
- Really clever to use this reasusable function - defo keep the code nice and tidy! 
https://github.com/ahoat/github-analyser/blob/f310144ef048201541adda6507af8983ae689a39/scripts.js#L33-L37

- What happens if you don't have this return at the end of the headlines function? Will the function not work without it? 
https://github.com/ahoat/github-analyser/blob/f310144ef048201541adda6507af8983ae689a39/scripts.js#L58

- Cool animations, CSS file it nice and uncluttered. Not much else to add - hope this is helpful 😅

**Comment by ahoat** [comment]
Thank you Maria!
the ` return; ` on line 58 isn't needed.
I was trying something so thanks for reminding me to delete it.
